### ISSUE TITLE
paddingTop hydration error

### ISSUE THREAD

**Issue by xHomu** [manawiki/mana#189]
![image](https://github.com/manawiki/core/assets/84349818/1f6e0b9c-634f-47e5-bcb2-acbdbbc011f8)

I was able to trace it down to this line:

https://github.com/manawiki/core/blob/725e28635363b32fe662a9b0ca47470aaa4ed813/app/routes/%24siteId%2B/_layout.tsx#L497

```jsx

                           <div
                              style={{
                                 paddingTop: safeArea?.top ?? "",
                              }}

```

comment it out clears the error, but I assume it's something Capacitor needs. What can we do to resolve this @pogseal ?

**Comment by pogseal** [comment]
Following should be the fix https://github.com/manawiki/core/commit/46a81e1bcdc8e6d0b91f6b9304c5581133a5df11
