### ISSUE TITLE
Custom Domain home page setup

### ISSUE THREAD

**Issue by pogseal** [manawiki/mana#202]
To determine if a site has a custom domain, check for `_/app/custom/config`

```
import { config } from "./app/_custom/config";
if (config.domain) then generate custom routes.
```

We only want to generate a route structure for the home (index) page.

**Comment by xHomu** [comment]
Basically, for custom sites we want to point to an alternative home page.  

Hypothetically, if user goes to,

https://starrail.wiki

We want them to actually see

https://starrail.wiki/starail 

without a redirect.

---

There are at least two ways to approach this:

* URL rewrite via the express server.ts: https://stackoverflow.com/questions/16579404/url-rewriting-with-expressjs
* inject the rule in remix.config routes prop: https://remix.run/docs/en/main/file-conventions/remix-config#routes

**Comment by xHomu** [comment]
Option A won't work because Remix doesn't support URL rewriting at all, so we'll have to go with Option B.

![image](https://github.com/manawiki/core/assets/84349818/aa85dce8-3087-4813-9c6d-3c06edb325ff)

**Comment by xHomu** [comment]
https://github.com/jacobparis-insiders/remix-custom-routes/tree/main/flatRoutes#implementation

brophdawg11:

> Not via the file conventions but you can point two paths to the same route file using the routes config: https://remix.run/docs/en/main/file-conventions/remix-config#routes.  By default the file path is the route id, so you need to specify a unique id for each when reusing.  I believe it's the third param to the route function IIRC, in the form of { id: "my-id" }
