### ISSUE TITLE
Slate Post Update broken

### ISSUE THREAD

**Issue by xHomu** [manawiki/mana#203]
When login with edit privileges, the post updates section are missing:

![image](https://github.com/manawiki/core/assets/84349818/56d4a9fe-5db1-4178-8f83-f84d8d32a789)

Shows dom error in logs:

![image](https://github.com/manawiki/core/assets/84349818/10ac9856-439e-4b86-ba46-734385b73164)

**Comment by xHomu** [comment]
Also, i think I accidentally deleted the existing post updates when testing this. 

ops

**Comment by pogseal** [comment]
Fixed, the console error is related to something else but also needs to be fixed.
