### ISSUE TITLE
Decrease Cache Duration for Logged-In Users

### ISSUE THREAD

**Issue by penguinstyles** [manawiki/mana#228]
Currently, the cache duration for logged-in users appears to be ridiculously high, which significantly impacts the editor's ability to quickly edit newly created/recently edited pages and causes potential data staleness.

While testing, I discovered that it takes roughly five minutes from the time a new entry is created within a collection to the time it displays to users. For anonymous users, five minutes should be sufficient, however, for logged-in users who always need to be shown the most up-to-date information available to prevent conflicting edits, we should reduce cache times.

**Comment by xHomu** [comment]
We can probably make it so if the request body contains user, skip the server cache?
